#manage: manage.cc problem-odb.cxx
	#g++ $^ -o $@ -lpthread -lfmt -lspdlog -lodb -lodb-boost -lodb-mysql -g
search: test_search.cc problem-odb.cxx
	g++ $^ -o $@ -lpthread -lfmt -lspdlog -lodb -lodb-boost -lodb-mysql -g
