/***********
 * input:
 * code: user's code
 * input: user's input, do not handle
 * cpu_limit and mem_limit, given by the designer
 * 
 * output:
 * status: compile error? system error? run error?
 * reason: string generated by status
 * stdout: result of the program
 * stderr: error infomation generated while running 
 * d************/
#pragma once
#include "compiler.hpp"
#include "runner.hpp"

#include <jsoncpp/json/json.h>

class CompileAndRun
{
private:
    static std::string ParseStatus(int status, std::string& filename)
    {
        std::string reason;
        std::string message;
        switch(status)
        {
        case 0:
            reason = "all normal";
            break;
        case 1:
            oj_utils::file_utils::read_file(oj_utils::name_utils::CompileError(filename), message, true);
            reason = "compile error: " + message;
            break;
        case 2:
            oj_utils::file_utils::read_file(oj_utils::name_utils::RunError(filename), message, true);
            if(message.empty())
            {
                message = "Segmentation fault (core dumped)";
            }
            reason = "run error: " + message;
            break;
        case -1:
            reason = "write into src fail";
            break;
        case -2:
            reason = "read stdout or stderr fail";
            break;
        default:
            reason = "Unknown error";
        }
        return reason;
    }

    static void remove_tmp(const std::string& filename)
    {
        std::string src_file = oj_utils::name_utils::Src(filename);
        std::string err_file = oj_utils::name_utils::CompileError(filename);
        std::string exe_file = oj_utils::name_utils::Exe(filename);
        std::string run_err_file = oj_utils::name_utils::RunError(filename);
        std::string stdin_file = oj_utils::name_utils::Stdin(filename);
        std::string stdout_file = oj_utils::name_utils::Stdout(filename);
        if(oj_utils::file_utils::cp_success(src_file))
        {
            unlink(src_file.c_str());
        }
        if(oj_utils::file_utils::cp_success(err_file))
        {
            unlink(err_file.c_str());
        }
        if(oj_utils::file_utils::cp_success(exe_file))
        {
            unlink(exe_file.c_str());
        }
        if(oj_utils::file_utils::cp_success(run_err_file))
        {
            unlink(run_err_file.c_str());
        }
        if(oj_utils::file_utils::cp_success(stdin_file))
        {
            unlink(stdin_file.c_str());
        }
        if(oj_utils::file_utils::cp_success(stdout_file))
        {
            unlink(stdout_file.c_str());
        }
    }
public:
    static void compile_and_run(const std::string& in_string, std::string& out_string)
    {
        Json::Value val; 
        Json::Reader reader;
        reader.parse(in_string, val);
        Json::Value out_json;

        std::string code = val["code"].asString();
        std::string input = val["input"].asString();
        int cpu_limit = val["cpu_limit"].asInt();
        int mem_limit = val["mem_limit"].asInt();

        int status = 0;
        std::string reason;
        std::string stdout;
        std::string stderr;

        std::string filename = oj_utils::file_utils::unique_file_name();
        if(!oj_utils::file_utils::write_file(oj_utils::name_utils::Src(filename), code))
        {
            status = -1;
            goto END;
        }
        if(!Compiler::compile(filename))
        {
            status = 1;
            goto END;
        }
        if(Runner::run(filename, cpu_limit, mem_limit) != 0)
        {
            status = 2;
            goto END;
        }
        
        if(!oj_utils::file_utils::read_file(oj_utils::name_utils::Stdout(filename), stdout, true) 
            || !oj_utils::file_utils::read_file(oj_utils::name_utils::RunError(filename), stderr, true))
        {
            status = -2;
        }
    END:
        reason = ParseStatus(status, filename);
        out_json["status"] = status; 
        out_json["reason"] = reason;
        out_json["stdout"] = stdout;
        out_json["stderr"] = stderr;
        Json::StyledWriter writer;
        out_string = writer.write(out_json);

        remove_tmp(filename);
    }
private:
};