/***********
 * input:
 * code: user's code
 * input: user's input, do not handle
 * cpu_limit and mem_limit, given by the designer
 * 
 * output:
 * status: compile error? system error? run error?
 * reason: string generated by status
 * stdout: result of the program
 * stderr: error infomation generated while running 
 * d************/
#include "compiler.hpp"
#include "runner.hpp"

#include <jsoncpp/json/json.h>

class CompileAndRun
{
private:
    static std::string ParseStatus(int status)
    {

    }
public:
    static void compile_and_run(const std::string& in_json, std::string& out_json)
    {
        Json::Value val; 
        Json::Reader reader;
        reader.parse(in_json, val);

        std::string code = val["code"].asString();
        std::string input = val["input"].asString();
        int cpu_limit = val["cpu_limit"].asInt();
        int mem_limit = val["mem_limit"].asInt();

        int status;
        std::string reason;
        std::string stdout;
        std::string stderr;

        std::string filename = oj_utils::file_utils::unique_file_name();
        if(!oj_utils::file_utils::write_file(oj_utils::name_utils::Src(filename), code))
        {
            status = -1;
            goto END;
        }
        if(!compiler.compile(filename))
        {
            status = 1;
            goto END;
        }
        if(!runner.run(filename, cpu_limit, mem_limit))
        {
            status = 2;
            goto END;
        }
        
        reason = ParseStatus(status);
        if(!oj_utils::file_utils::read_file(oj_utils::name_utils::Stdout(filename), stdout, true) 
            || !oj_utils::file_utils::read_file(oj_utils::name_utils::RunError(filename), stderr, true))
        {
            status = -2;
        }
    END:
    }
private:
    static Compiler compiler;
    static Runner runner;
};